### PR TITLE
Added Ginny, Daphne & Extra Assets

### PR DESCRIPTION
**Pull request by Ayyy-Lmao**
- Added Daphne from Sad Crab's WT 1.6
- Added Ginny custom skin
- Added assets left out from WT 1.6 and WT Silver
- Added custom clothing
- Added backdrops to all HP characters
- fixed some missing/bugged clothing items

### CODE REVIEW

**Comment by moldred** [comment]
where is that accessible? I don't see it in  stregac/trainers_image_library

**Comment by zddguu** [comment]
It's still a request, so the changes haven't been accepted yet. That being said, you can get Ayyy-Lmao's tree by going to his page: https://github.com/Ayyy-Lmao/trainers_image_library/tree/adding-assets and downloading it there. This project works with Javascript, so you should just be able to open the index.html file in a web browser.

**Comment by Onyxdime** [comment]
Hey, I'm looking to commission a lot of clothing and poses for this project. Does anyone know any artists who are working on this Hermione dresser?

I know this isn't the right place to post it, but I was at a loss for where else to go.

**Comment by zddguu** [comment]
Try emailing stregac@yandex.com to see who originally drew the extra clothing sets, and get in contact with them. Akabur is the original creator of this project, so you could try an email to convince him to create more art; he makes 6 grand a month on Patreon, though, so good luck. /DAHR, also on Patreon does art work with/for Akabur and makes considerably less, so he might be a good candidate. As a last resort, post on the /aco/ general, there's usually a few lurkers who've done sets for this project and might be interested in paid work.

**Comment by stregac** [comment]
@Ayyy-Lmao we're getting back to the project, will take a look at your branch. Thank you for your cooperation! :-)

**Comment by atomicgator** [comment]
No prob!

Which branch should I be working with from now on?

**Comment by stregac** [comment]
@atomicgator wherever works best for you :-) the official one is `gh-pages`. Just remember to open a Pull Request over here.

**Pull request merged**
