### PR TITLE
coding and contents

### PR DESCRIPTION
**Pull request by anxtdghiov**
One of my patches touches many images to autocrop them while preserving offset. This improves display of buttons on the website, but has implications if you want to later edit them. Not sure if this is desireable. The patch description indicates how this can  be undone.

### CODE REVIEW

**Comment by stregac** [comment]
Thank you, I will be investigating this in a few days.

**Comment by potusman** [comment]
Stregac could you please add this content

**Comment by stregac** [comment]
Unfortunately changing all images would be troublesome for some friends using this library. So we decided to go ahead and merge the best items from your branch at https://github.com/stregac/trainers_image_library/commit/7068e296d605352d13c1c309edcb855d2467bfb1. Thank you very much for helping the library!

**Comment by moldred** [comment]
if you're SILVER or slavetrainermod
This suddenly started happening during personal favour "Let me touch them" The programming behind the game. Now it happens on every scene on the left part of the screen.  Did I press a wrong button or something? 
Otherwise what's his github name?

**Pull request closed without merging**
